### ISSUE TITLE
Solve reCaptcha with selenium

### ISSUE THREAD

**Issue by Altimis** [NopeCHALLC/nopecha-scripts#2]
Hi guys, can we solve reCaptcha in the middle of a selenium process please ?

**Comment by oyunvfg** [comment]
I think I was scammed. I wish I had read this before.

**Comment by NopeCHALLC** [comment]
Yes, both the [Chrome extension](https://nopecha.com/chrome) and [Firefox Add-on](https://nopecha.com/firefox) works with Selenium and all other browser automation tools.

Please refer to the [documentation and guide](https://developers.nopecha.com/) for more information.
